### ISSUE TITLE
Crawled URL not working in Widget

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-siteimprove#31] opened 2019-02-27 14:28 UTC
Siteimprove confirms this URL is crawled:
https://enonic.com/blog/headless-cms-expectations-vs-reality

But it still showing as not crawled in the widget:
Siteimprove statistics are not available for "https://enonic.com/blog/headless-cms-expectations-vs-reality".

This happens with a range of pages.

**Comment by alansemenov** [comment] 2019-02-28 09:26
Duplicate of #29

**Closed by alansemenov** 2019-02-28 09:26 UTC
